// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './AaveV3.sol';
import {ICollector} from './common/ICollector.sol';

library AaveV3FantomTestnet {
  // https://testnet.ftmscan.com/address/0xBe8d95E9e8F6B852371b21dc3Ce36CF9440a64C0
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0xBe8d95E9e8F6B852371b21dc3Ce36CF9440a64C0);

  // https://testnet.ftmscan.com/address/0x9c19e7cB4854C0E8EC6fD4fC4539e093c8022cF6
  IPool internal constant POOL = IPool(0x9c19e7cB4854C0E8EC6fD4fC4539e093c8022cF6);

  // https://testnet.ftmscan.com/address/0x98578d751EA96C593235d754B2688b6b0c7cC6A9
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x98578d751EA96C593235d754B2688b6b0c7cC6A9);

  // https://testnet.ftmscan.com/address/0x410F8C1eb2fCc43f7a87a276b8838a381c6e4d81
  IAaveOracle internal constant ORACLE = IAaveOracle(0x410F8C1eb2fCc43f7a87a276b8838a381c6e4d81);

  // https://testnet.ftmscan.com/address/0x0000000000000000000000000000000000000000
  address internal constant PRICE_ORACLE_SENTINEL = 0x0000000000000000000000000000000000000000;

  // https://testnet.ftmscan.com/address/0x5b779b731123B41a40fFA8223e1b787fBb449126
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x5b779b731123B41a40fFA8223e1b787fBb449126);

  // https://testnet.ftmscan.com/address/0x28f537fd3C43Cf02ce727f4348Ad252b1A2cd0F2
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0x28f537fd3C43Cf02ce727f4348Ad252b1A2cd0F2);

  // https://testnet.ftmscan.com/address/0x9dd64152E20372B2C4D8982e2b174D0C84f07D29
  address internal constant ACL_ADMIN = 0x9dd64152E20372B2C4D8982e2b174D0C84f07D29;

  // https://testnet.ftmscan.com/address/0x92165033a0FF62DE8F255DE2127A9d8C84bF73A3
  ICollector internal constant COLLECTOR = ICollector(0x92165033a0FF62DE8F255DE2127A9d8C84bF73A3);

  // https://testnet.ftmscan.com/address/0xfAaD7b5E633DBE891DF99581053615EE695e272B
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0xfAaD7b5E633DBE891DF99581053615EE695e272B;

  // https://testnet.ftmscan.com/address/0xF35b50211ee99D552eE5FfeAE59ef85F19157Ad8
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0xF35b50211ee99D552eE5FfeAE59ef85F19157Ad8;

  // https://testnet.ftmscan.com/address/0x4b599c46189C6B09882223Ac1AA661EfD7A0b817
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x4b599c46189C6B09882223Ac1AA661EfD7A0b817;

  // https://testnet.ftmscan.com/address/0x756d924f916C3a987d47342F72736a387603Cf11
  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x756d924f916C3a987d47342F72736a387603Cf11;

  // https://testnet.ftmscan.com/address/0xe47035C20Ae518d282602080DF299d83DEd27091
  address internal constant EMISSION_MANAGER = 0xe47035C20Ae518d282602080DF299d83DEd27091;

  // https://testnet.ftmscan.com/address/0xb78F1d73EDF017f236b7617EE3b0159873962447
  address internal constant FAUCET = 0xb78F1d73EDF017f236b7617EE3b0159873962447;

  // https://testnet.ftmscan.com/address/0xBE3aC3487AA875d16FDE1204337175e7e85dD0A6
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0xBE3aC3487AA875d16FDE1204337175e7e85dD0A6;

  // https://testnet.ftmscan.com/address/0x8F505faa8cbF0a8D1a65c21534C96bCbE8521B97
  address internal constant UI_POOL_DATA_PROVIDER = 0x8F505faa8cbF0a8D1a65c21534C96bCbE8521B97;

  // https://testnet.ftmscan.com/address/0xD746946f53cDcCDEE8e993E29EA257BE366649d1
  address internal constant WALLET_BALANCE_PROVIDER = 0xD746946f53cDcCDEE8e993E29EA257BE366649d1;

  // https://testnet.ftmscan.com/address/0x201891DF02d3098C9dD051CC01ae3a8Ce48fe016
  address internal constant WETH_GATEWAY = 0x201891DF02d3098C9dD051CC01ae3a8Ce48fe016;
}

library AaveV3FantomTestnetAssets {
  // https://testnet.ftmscan.com/address/0xcF1F89126cdA301A64976083CBeA0cA2E22a3d71
  address internal constant DAI_UNDERLYING = 0xcF1F89126cdA301A64976083CBeA0cA2E22a3d71;

  uint8 internal constant DAI_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0xEc1DBE9e5BfFe8010fDCe7D60B139404Ea10ed12
  address internal constant DAI_A_TOKEN = 0xEc1DBE9e5BfFe8010fDCe7D60B139404Ea10ed12;

  // https://testnet.ftmscan.com/address/0xB4CB5Bf8E327c78849baB6E952D3f290F7117762
  address internal constant DAI_V_TOKEN = 0xB4CB5Bf8E327c78849baB6E952D3f290F7117762;

  // https://testnet.ftmscan.com/address/0x002d6f0541D84b0217Ce70175F9bDee695cC1208
  address internal constant DAI_S_TOKEN = 0x002d6f0541D84b0217Ce70175F9bDee695cC1208;

  // https://testnet.ftmscan.com/address/0xB5e622f44A865D0d6dFe8B06b22a2E9C4B7733F8
  address internal constant DAI_ORACLE = 0xB5e622f44A865D0d6dFe8B06b22a2E9C4B7733F8;

  // https://testnet.ftmscan.com/address/0x58230c6DEBd8B5220a57Efb022A74794c6d98952
  address internal constant DAI_INTEREST_RATE_STRATEGY = 0x58230c6DEBd8B5220a57Efb022A74794c6d98952;

  // https://testnet.ftmscan.com/address/0x9f5d17A6361759e535b456dacD0B568668D2ba00
  address internal constant LINK_UNDERLYING = 0x9f5d17A6361759e535b456dacD0B568668D2ba00;

  uint8 internal constant LINK_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0xe2088a776a4a464462D326FAFd1AA2da900C9F89
  address internal constant LINK_A_TOKEN = 0xe2088a776a4a464462D326FAFd1AA2da900C9F89;

  // https://testnet.ftmscan.com/address/0xBfD186dd08fB7f911d67E70c6c095E621214Be14
  address internal constant LINK_V_TOKEN = 0xBfD186dd08fB7f911d67E70c6c095E621214Be14;

  // https://testnet.ftmscan.com/address/0x9C5bdd05b54368fFcE32f24cBE8Eb9518859Ad5B
  address internal constant LINK_S_TOKEN = 0x9C5bdd05b54368fFcE32f24cBE8Eb9518859Ad5B;

  // https://testnet.ftmscan.com/address/0xfa889ad72b623BBFA0A3E186385A807c68f4f9A3
  address internal constant LINK_ORACLE = 0xfa889ad72b623BBFA0A3E186385A807c68f4f9A3;

  // https://testnet.ftmscan.com/address/0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0
  address internal constant LINK_INTEREST_RATE_STRATEGY =
    0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0;

  // https://testnet.ftmscan.com/address/0xcd308B2F84B9186FB3ec5c95C674c651c862C405
  address internal constant USDC_UNDERLYING = 0xcd308B2F84B9186FB3ec5c95C674c651c862C405;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://testnet.ftmscan.com/address/0xa8e86844e6576f247D36e12069C69F67713942F3
  address internal constant USDC_A_TOKEN = 0xa8e86844e6576f247D36e12069C69F67713942F3;

  // https://testnet.ftmscan.com/address/0x3ebdC77F20C768CeFDB95255530d55508c71919F
  address internal constant USDC_V_TOKEN = 0x3ebdC77F20C768CeFDB95255530d55508c71919F;

  // https://testnet.ftmscan.com/address/0xa57f1c7365871Faea286aB71f529E3cba0DFc941
  address internal constant USDC_S_TOKEN = 0xa57f1c7365871Faea286aB71f529E3cba0DFc941;

  // https://testnet.ftmscan.com/address/0x7f5E27235414f152a7956070acDFBb9aBc80f017
  address internal constant USDC_ORACLE = 0x7f5E27235414f152a7956070acDFBb9aBc80f017;

  // https://testnet.ftmscan.com/address/0x31De0156e88bEF3489C72A68b189379edD34dC49
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x31De0156e88bEF3489C72A68b189379edD34dC49;

  // https://testnet.ftmscan.com/address/0x508Ed1616d13D0db963020bFc4C10e236a7fb005
  address internal constant WBTC_UNDERLYING = 0x508Ed1616d13D0db963020bFc4C10e236a7fb005;

  uint8 internal constant WBTC_DECIMALS = 8;

  // https://testnet.ftmscan.com/address/0x0Ea4531E4E3Adc051D4933524999C8c7B49cAC72
  address internal constant WBTC_A_TOKEN = 0x0Ea4531E4E3Adc051D4933524999C8c7B49cAC72;

  // https://testnet.ftmscan.com/address/0x1B6e5C8c5AD9d9b38e5F51425Ad18975b5a5534D
  address internal constant WBTC_V_TOKEN = 0x1B6e5C8c5AD9d9b38e5F51425Ad18975b5a5534D;

  // https://testnet.ftmscan.com/address/0x1a002f0112e3bd15218C59920Ba158820d9C330B
  address internal constant WBTC_S_TOKEN = 0x1a002f0112e3bd15218C59920Ba158820d9C330B;

  // https://testnet.ftmscan.com/address/0x561ceF8e20e934a0d3392DDc73f4468B39D12980
  address internal constant WBTC_ORACLE = 0x561ceF8e20e934a0d3392DDc73f4468B39D12980;

  // https://testnet.ftmscan.com/address/0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0
  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0;

  // https://testnet.ftmscan.com/address/0xfa698e167bcCF7D33BE180f9944174573B276Ae7
  address internal constant WETH_UNDERLYING = 0xfa698e167bcCF7D33BE180f9944174573B276Ae7;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0x5AC835705BbfD18B9B74CF245f89E72A049cE53d
  address internal constant WETH_A_TOKEN = 0x5AC835705BbfD18B9B74CF245f89E72A049cE53d;

  // https://testnet.ftmscan.com/address/0x4E3d032a0B64f2548142442C37F4832935F6C3cF
  address internal constant WETH_V_TOKEN = 0x4E3d032a0B64f2548142442C37F4832935F6C3cF;

  // https://testnet.ftmscan.com/address/0x99890Eb76cB19f25EA57d795E2557136F214D424
  address internal constant WETH_S_TOKEN = 0x99890Eb76cB19f25EA57d795E2557136F214D424;

  // https://testnet.ftmscan.com/address/0x31da2bfB163A16E830aDFD92c5f59d1762eF80ad
  address internal constant WETH_ORACLE = 0x31da2bfB163A16E830aDFD92c5f59d1762eF80ad;

  // https://testnet.ftmscan.com/address/0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0;

  // https://testnet.ftmscan.com/address/0x342dA39FD5983B38b1905E8192D6574769260EF5
  address internal constant USDT_UNDERLYING = 0x342dA39FD5983B38b1905E8192D6574769260EF5;

  uint8 internal constant USDT_DECIMALS = 6;

  // https://testnet.ftmscan.com/address/0xad4777Fb45d37a0D312e29e386237CFEc37c77C4
  address internal constant USDT_A_TOKEN = 0xad4777Fb45d37a0D312e29e386237CFEc37c77C4;

  // https://testnet.ftmscan.com/address/0xe207420C60ac4E53011E8B1780501A100cE3788a
  address internal constant USDT_V_TOKEN = 0xe207420C60ac4E53011E8B1780501A100cE3788a;

  // https://testnet.ftmscan.com/address/0x379bC09Ae6aBF39995C717A66Aa303e5e21594c9
  address internal constant USDT_S_TOKEN = 0x379bC09Ae6aBF39995C717A66Aa303e5e21594c9;

  // https://testnet.ftmscan.com/address/0xFE370321745A99f6d04396C09aC1BA22A9d5909B
  address internal constant USDT_ORACLE = 0xFE370321745A99f6d04396C09aC1BA22A9d5909B;

  // https://testnet.ftmscan.com/address/0x31De0156e88bEF3489C72A68b189379edD34dC49
  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0x31De0156e88bEF3489C72A68b189379edD34dC49;

  // https://testnet.ftmscan.com/address/0x40d91bF3FC4523010848215319E14a2430601884
  address internal constant AAVE_UNDERLYING = 0x40d91bF3FC4523010848215319E14a2430601884;

  uint8 internal constant AAVE_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0x4FBf266CE6450593A97aFc4CDAaC6464220af392
  address internal constant AAVE_A_TOKEN = 0x4FBf266CE6450593A97aFc4CDAaC6464220af392;

  // https://testnet.ftmscan.com/address/0x1977411c3076b3E24F735315753472E62970D2Cb
  address internal constant AAVE_V_TOKEN = 0x1977411c3076b3E24F735315753472E62970D2Cb;

  // https://testnet.ftmscan.com/address/0xC81df892b679A92Adc0378b73A81beDbf9810fD4
  address internal constant AAVE_S_TOKEN = 0xC81df892b679A92Adc0378b73A81beDbf9810fD4;

  // https://testnet.ftmscan.com/address/0x104658E5b85B80B757189725e3992332d080d42E
  address internal constant AAVE_ORACLE = 0x104658E5b85B80B757189725e3992332d080d42E;

  // https://testnet.ftmscan.com/address/0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0
  address internal constant AAVE_INTEREST_RATE_STRATEGY =
    0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0;

  // https://testnet.ftmscan.com/address/0x9f031C6a25b4D261208f95900afD5bC66036398c
  address internal constant WFTM_UNDERLYING = 0x9f031C6a25b4D261208f95900afD5bC66036398c;

  uint8 internal constant WFTM_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0xc772D0984f6964f92595626CD5452f08f133F596
  address internal constant WFTM_A_TOKEN = 0xc772D0984f6964f92595626CD5452f08f133F596;

  // https://testnet.ftmscan.com/address/0x4238659B8Cf770F3a7a0483701C0e615Deeab14a
  address internal constant WFTM_V_TOKEN = 0x4238659B8Cf770F3a7a0483701C0e615Deeab14a;

  // https://testnet.ftmscan.com/address/0x4E5De8e97b5be816cE57D4865621746706283059
  address internal constant WFTM_S_TOKEN = 0x4E5De8e97b5be816cE57D4865621746706283059;

  // https://testnet.ftmscan.com/address/0xC63F835c841249B8B172507f2B00B68bc24f3D22
  address internal constant WFTM_ORACLE = 0xC63F835c841249B8B172507f2B00B68bc24f3D22;

  // https://testnet.ftmscan.com/address/0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0
  address internal constant WFTM_INTEREST_RATE_STRATEGY =
    0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0;

  // https://testnet.ftmscan.com/address/0x3E1ff6b26A6ddF68A211839698E7470399b688CD
  address internal constant CRV_UNDERLYING = 0x3E1ff6b26A6ddF68A211839698E7470399b688CD;

  uint8 internal constant CRV_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0xEd4b9eD83D4D85A0da1177a38E7b9fCe1887664E
  address internal constant CRV_A_TOKEN = 0xEd4b9eD83D4D85A0da1177a38E7b9fCe1887664E;

  // https://testnet.ftmscan.com/address/0xc6B5658bcead798Ee8C4fa6C4bD7fEf3e33EF832
  address internal constant CRV_V_TOKEN = 0xc6B5658bcead798Ee8C4fa6C4bD7fEf3e33EF832;

  // https://testnet.ftmscan.com/address/0xA26344886e32B73EFE009FeF4c100456b59Cf636
  address internal constant CRV_S_TOKEN = 0xA26344886e32B73EFE009FeF4c100456b59Cf636;

  // https://testnet.ftmscan.com/address/0x0bE284e40B94408cF7F6d48048Cd661Cc7894912
  address internal constant CRV_ORACLE = 0x0bE284e40B94408cF7F6d48048Cd661Cc7894912;

  // https://testnet.ftmscan.com/address/0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0
  address internal constant CRV_INTEREST_RATE_STRATEGY = 0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0;

  // https://testnet.ftmscan.com/address/0x094cfb21d619375d9204e4de89Eaa3BAE48E5BD7
  address internal constant SUSHI_UNDERLYING = 0x094cfb21d619375d9204e4de89Eaa3BAE48E5BD7;

  uint8 internal constant SUSHI_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0xaD3E8C272547b1E6443C5B9da3A944C0B3dB81F4
  address internal constant SUSHI_A_TOKEN = 0xaD3E8C272547b1E6443C5B9da3A944C0B3dB81F4;

  // https://testnet.ftmscan.com/address/0x1BC154D4376d8e7B804eAC05C6a74Fc44331736a
  address internal constant SUSHI_V_TOKEN = 0x1BC154D4376d8e7B804eAC05C6a74Fc44331736a;

  // https://testnet.ftmscan.com/address/0xA15E7F1B3E6D4D2ba1ecc32Fa70fe382EAD00984
  address internal constant SUSHI_S_TOKEN = 0xA15E7F1B3E6D4D2ba1ecc32Fa70fe382EAD00984;

  // https://testnet.ftmscan.com/address/0xd0EaFDbC1157ee8678441490c534a34aF62a8D87
  address internal constant SUSHI_ORACLE = 0xd0EaFDbC1157ee8678441490c534a34aF62a8D87;

  // https://testnet.ftmscan.com/address/0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0
  address internal constant SUSHI_INTEREST_RATE_STRATEGY =
    0xCB5FBd8eC063A0a9b44DD32afD488e468fD114D0;
}

library AaveV3FantomTestnetEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant STABLECOINS = 1;
}
