// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './AaveV3.sol';
import {ICollector} from './common/ICollector.sol';

library AaveV3FantomTestnet {
  // https://testnet.ftmscan.com/address/0x5592D3333729f2e2753d351568Ab0dF0932A6dcE
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x5592D3333729f2e2753d351568Ab0dF0932A6dcE);

  // https://testnet.ftmscan.com/address/0x8A68E843ecA1c5aA7fE105334A3F0f2417229950
  IPool internal constant POOL = IPool(0x8A68E843ecA1c5aA7fE105334A3F0f2417229950);

  // https://testnet.ftmscan.com/address/0x57513B5aadD0e094b6ccfDc368Ac194C1F030cD9
  address internal constant POOL_IMPL = 0x57513B5aadD0e094b6ccfDc368Ac194C1F030cD9;

  // https://testnet.ftmscan.com/address/0xEA9807fA05802CDB670d54795eAF7b6a4db50A2E
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0xEA9807fA05802CDB670d54795eAF7b6a4db50A2E);

  // https://testnet.ftmscan.com/address/0xc3bD95c90Af0D39DdD9A0EE7F3a542638Aa4934f
  address internal constant POOL_CONFIGURATOR_IMPL = 0xc3bD95c90Af0D39DdD9A0EE7F3a542638Aa4934f;

  // https://testnet.ftmscan.com/address/0x4e91f374a26AC76C80CfDdC00AC65789bD0849Da
  IAaveOracle internal constant ORACLE = IAaveOracle(0x4e91f374a26AC76C80CfDdC00AC65789bD0849Da);

  // https://testnet.ftmscan.com/address/0xd9771d0535009198e3192BfCFE2bc8Eef08B8439
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0xd9771d0535009198e3192BfCFE2bc8Eef08B8439);

  // https://testnet.ftmscan.com/address/0xf3F752E1de16b955D0B0858Bd3AfA514d59eCdF6
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0xf3F752E1de16b955D0B0858Bd3AfA514d59eCdF6);

  // https://testnet.ftmscan.com/address/0x9dd64152E20372B2C4D8982e2b174D0C84f07D29
  address internal constant ACL_ADMIN = 0x9dd64152E20372B2C4D8982e2b174D0C84f07D29;

  // https://testnet.ftmscan.com/address/0x1F8e6C2737012FbF71e037311f1C8C961DFBBb88
  ICollector internal constant COLLECTOR = ICollector(0x1F8e6C2737012FbF71e037311f1C8C961DFBBb88);

  // https://testnet.ftmscan.com/address/0xF862B5f843eB3C243a19506d2d88166E32174ec6
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0xF862B5f843eB3C243a19506d2d88166E32174ec6;

  // https://testnet.ftmscan.com/address/0x922aF43233dcB3348800e34d901d6839ED8dA132
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x922aF43233dcB3348800e34d901d6839ED8dA132;

  // https://testnet.ftmscan.com/address/0x8F769e52B986531064E06F38a93675fAAcD63324
  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x8F769e52B986531064E06F38a93675fAAcD63324;

  // https://testnet.ftmscan.com/address/0x2261B7BD07Ece22e851c0Ba0664cC185cd10948C
  address internal constant FAUCET = 0x2261B7BD07Ece22e851c0Ba0664cC185cd10948C;

  // https://testnet.ftmscan.com/address/0x5fbE5fD248a6634C1F498e188f1Bb27629b359e9
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x5fbE5fD248a6634C1F498e188f1Bb27629b359e9;

  // https://testnet.ftmscan.com/address/0x1DE1C2549ab5A17DF9Bf050De219f5Cb78C881Af
  address internal constant UI_POOL_DATA_PROVIDER = 0x1DE1C2549ab5A17DF9Bf050De219f5Cb78C881Af;

  // https://testnet.ftmscan.com/address/0x4AC0c7ACdeEC1BF6b67C098cF933A78635607e59
  address internal constant WALLET_BALANCE_PROVIDER = 0x4AC0c7ACdeEC1BF6b67C098cF933A78635607e59;

  // https://testnet.ftmscan.com/address/0x8973023334498586746587bBd82d8F309e4CB1e9
  address internal constant WETH_GATEWAY = 0x8973023334498586746587bBd82d8F309e4CB1e9;
}

library AaveV3FantomTestnetAssets {
  // https://testnet.ftmscan.com/address/0x8EEB7426eaD92914fA466B6B39767e98C01C8EE9
  address internal constant LINK_UNDERLYING = 0x8EEB7426eaD92914fA466B6B39767e98C01C8EE9;

  uint8 internal constant LINK_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0x9F2E45d48E726824aA18A572D773C89Ea2977ae6
  address internal constant LINK_A_TOKEN = 0x9F2E45d48E726824aA18A572D773C89Ea2977ae6;

  // https://testnet.ftmscan.com/address/0x17c75B3AE835d4788FedC31909252d7b7bc4Be35
  address internal constant LINK_V_TOKEN = 0x17c75B3AE835d4788FedC31909252d7b7bc4Be35;

  // https://testnet.ftmscan.com/address/0xec9200C690B1D65D53547b7671c3991A90CC721C
  address internal constant LINK_S_TOKEN = 0xec9200C690B1D65D53547b7671c3991A90CC721C;

  // https://testnet.ftmscan.com/address/0x6d5689Ad4C1806D1BA0c70Ab95ebe0Da6B204fC5
  address internal constant LINK_ORACLE = 0x6d5689Ad4C1806D1BA0c70Ab95ebe0Da6B204fC5;

  // https://testnet.ftmscan.com/address/0x861A455F65a877c00F9C3bA922ec7ea808f9c07D
  address internal constant LINK_INTEREST_RATE_STRATEGY =
    0x861A455F65a877c00F9C3bA922ec7ea808f9c07D;

  // https://testnet.ftmscan.com/address/0x4968dAb483AB23872821D24D7f88cA4C6C2D99e1
  address internal constant WBTC_UNDERLYING = 0x4968dAb483AB23872821D24D7f88cA4C6C2D99e1;

  uint8 internal constant WBTC_DECIMALS = 8;

  // https://testnet.ftmscan.com/address/0x51BAd5C2c0C8Fe9D795A8B3Ccd3871D0d467C179
  address internal constant WBTC_A_TOKEN = 0x51BAd5C2c0C8Fe9D795A8B3Ccd3871D0d467C179;

  // https://testnet.ftmscan.com/address/0x8C482d753f00EFcCd4da6daeffCfc94D2C047BE9
  address internal constant WBTC_V_TOKEN = 0x8C482d753f00EFcCd4da6daeffCfc94D2C047BE9;

  // https://testnet.ftmscan.com/address/0x10bD592EBca70a73069F0DBDe946d61712e3442b
  address internal constant WBTC_S_TOKEN = 0x10bD592EBca70a73069F0DBDe946d61712e3442b;

  // https://testnet.ftmscan.com/address/0x65E8d79f3e8e36fE48eC31A2ae935e92F5bBF529
  address internal constant WBTC_ORACLE = 0x65E8d79f3e8e36fE48eC31A2ae935e92F5bBF529;

  // https://testnet.ftmscan.com/address/0x861A455F65a877c00F9C3bA922ec7ea808f9c07D
  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0x861A455F65a877c00F9C3bA922ec7ea808f9c07D;

  // https://testnet.ftmscan.com/address/0x0F12fd2495918a4dC4345e94BDe248274B993740
  address internal constant WETH_UNDERLYING = 0x0F12fd2495918a4dC4345e94BDe248274B993740;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0xD7f8978397D3b63418d392bD4a9870F63F4f34dD
  address internal constant WETH_A_TOKEN = 0xD7f8978397D3b63418d392bD4a9870F63F4f34dD;

  // https://testnet.ftmscan.com/address/0x79b5FE646548CC61AcC5AA15B7E26A1d6818958e
  address internal constant WETH_V_TOKEN = 0x79b5FE646548CC61AcC5AA15B7E26A1d6818958e;

  // https://testnet.ftmscan.com/address/0xC2Badb6153CCF751Ddc3A8c1d98993C535b8C462
  address internal constant WETH_S_TOKEN = 0xC2Badb6153CCF751Ddc3A8c1d98993C535b8C462;

  // https://testnet.ftmscan.com/address/0xB8C458C957a6e6ca7Cc53eD95bEA548c52AFaA24
  address internal constant WETH_ORACLE = 0xB8C458C957a6e6ca7Cc53eD95bEA548c52AFaA24;

  // https://testnet.ftmscan.com/address/0x861A455F65a877c00F9C3bA922ec7ea808f9c07D
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x861A455F65a877c00F9C3bA922ec7ea808f9c07D;

  // https://testnet.ftmscan.com/address/0xc7DdDe830db19Bd94DD584dCAC774f0Be47B29d1
  address internal constant USDT_UNDERLYING = 0xc7DdDe830db19Bd94DD584dCAC774f0Be47B29d1;

  uint8 internal constant USDT_DECIMALS = 6;

  // https://testnet.ftmscan.com/address/0x0eA1eD91A9651e52CaF4c739b89c73c65FeBF417
  address internal constant USDT_A_TOKEN = 0x0eA1eD91A9651e52CaF4c739b89c73c65FeBF417;

  // https://testnet.ftmscan.com/address/0x394F34e10325e911c277C5aEe70097619e4de00A
  address internal constant USDT_V_TOKEN = 0x394F34e10325e911c277C5aEe70097619e4de00A;

  // https://testnet.ftmscan.com/address/0x0aA0395f5E534e71924EC0Ac5363869fD8bA856D
  address internal constant USDT_S_TOKEN = 0x0aA0395f5E534e71924EC0Ac5363869fD8bA856D;

  // https://testnet.ftmscan.com/address/0x9BB8A6dcD83E36726Cc230a97F1AF8a84ae5F128
  address internal constant USDT_ORACLE = 0x9BB8A6dcD83E36726Cc230a97F1AF8a84ae5F128;

  // https://testnet.ftmscan.com/address/0xd1F6b64f5b87A86732d1b0B3DE65629CF4568926
  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0xd1F6b64f5b87A86732d1b0B3DE65629CF4568926;

  // https://testnet.ftmscan.com/address/0xE8175A3C1Dd1337aD276a8105ae6375367bf620B
  address internal constant WFTM_UNDERLYING = 0xE8175A3C1Dd1337aD276a8105ae6375367bf620B;

  uint8 internal constant WFTM_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0x3395658FDD5b973d1A9554436d73461B210ebA43
  address internal constant WFTM_A_TOKEN = 0x3395658FDD5b973d1A9554436d73461B210ebA43;

  // https://testnet.ftmscan.com/address/0x16a40EfA32253031Ef464Ce963077b47Da8F47dD
  address internal constant WFTM_V_TOKEN = 0x16a40EfA32253031Ef464Ce963077b47Da8F47dD;

  // https://testnet.ftmscan.com/address/0x7BCbA6B7011A71c82c4aDEC3e2b853152569C386
  address internal constant WFTM_S_TOKEN = 0x7BCbA6B7011A71c82c4aDEC3e2b853152569C386;

  // https://testnet.ftmscan.com/address/0xe04676B9A9A2973BCb0D1478b5E1E9098BBB7f3D
  address internal constant WFTM_ORACLE = 0xe04676B9A9A2973BCb0D1478b5E1E9098BBB7f3D;

  // https://testnet.ftmscan.com/address/0x861A455F65a877c00F9C3bA922ec7ea808f9c07D
  address internal constant WFTM_INTEREST_RATE_STRATEGY =
    0x861A455F65a877c00F9C3bA922ec7ea808f9c07D;
}

library AaveV3FantomTestnetEModes {
  uint8 internal constant NONE = 0;
}
