// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager} from './AaveV3.sol';
import {ICollector} from './common/ICollector.sol';

library AaveV3FantomTestnet {
  // https://testnet.ftmscan.com/address/0x1157237B2cf48adb612329671D5FcB48DC980B4B
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x1157237B2cf48adb612329671D5FcB48DC980B4B);

  // https://testnet.ftmscan.com/address/0x692E995C17200aaC2BE2E2f4E879b7762eC1d4bb
  IPool internal constant POOL = IPool(0x692E995C17200aaC2BE2E2f4E879b7762eC1d4bb);

  // https://testnet.ftmscan.com/address/0xB73F346a92172bF85C4b14ffcFd9Df86E10f7376
  address internal constant POOL_IMPL = 0xB73F346a92172bF85C4b14ffcFd9Df86E10f7376;

  // https://testnet.ftmscan.com/address/0x642C744Df4E8c2cfEb044fc1984C6c0cfA29890B
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0x642C744Df4E8c2cfEb044fc1984C6c0cfA29890B);

  // https://testnet.ftmscan.com/address/0x5952c1690EA1669bb32aF239503d3b0bCA96FAe7
  address internal constant POOL_CONFIGURATOR_IMPL = 0x5952c1690EA1669bb32aF239503d3b0bCA96FAe7;

  // https://testnet.ftmscan.com/address/0xb4e9901a5C29f9acC607c49867dFDC0A92C25E49
  IAaveOracle internal constant ORACLE = IAaveOracle(0xb4e9901a5C29f9acC607c49867dFDC0A92C25E49);

  // https://testnet.ftmscan.com/address/0x806264B38BEb2E5f9A0207B0A4d8A73f5f041205
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0x806264B38BEb2E5f9A0207B0A4d8A73f5f041205);

  // https://testnet.ftmscan.com/address/0xe2E3eCE41A29cBcf2a7a198F30De6185Bc6CB3C3
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0xe2E3eCE41A29cBcf2a7a198F30De6185Bc6CB3C3);

  // https://testnet.ftmscan.com/address/0x9dd64152E20372B2C4D8982e2b174D0C84f07D29
  address internal constant ACL_ADMIN = 0x9dd64152E20372B2C4D8982e2b174D0C84f07D29;

  // https://testnet.ftmscan.com/address/0x57f46e6eE23882F995eFE32ca2ee2A7b762e84Bb
  ICollector internal constant COLLECTOR = ICollector(0x57f46e6eE23882F995eFE32ca2ee2A7b762e84Bb);

  // https://testnet.ftmscan.com/address/0x784220cCEE9002227f52fB257AA1FEa25de73b2C
  address internal constant DEFAULT_A_TOKEN_IMPL_REV_1 = 0x784220cCEE9002227f52fB257AA1FEa25de73b2C;

  // https://testnet.ftmscan.com/address/0x6d8BE31e17c5388e296A8E4d2e371a0dBFb75ccA
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL_REV_1 =
    0x6d8BE31e17c5388e296A8E4d2e371a0dBFb75ccA;

  // https://testnet.ftmscan.com/address/0xC96882345c2c9B8B7450eBCf6CE1c98417335a8F
  address internal constant DEFAULT_STABLE_DEBT_TOKEN_IMPL_REV_1 =
    0xC96882345c2c9B8B7450eBCf6CE1c98417335a8F;

  // https://testnet.ftmscan.com/address/0x1b0cF5697Dd9b087a2213aCc059ef4211B9f5eB1
  address internal constant FAUCET = 0x1b0cF5697Dd9b087a2213aCc059ef4211B9f5eB1;

  // https://testnet.ftmscan.com/address/0x978855a8f269EC8dDc96513c5974a9185D5a1b4A
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x978855a8f269EC8dDc96513c5974a9185D5a1b4A;

  // https://testnet.ftmscan.com/address/0x69256C3EB7b657c8aF0d51Cf6e462b09b94C45ec
  address internal constant UI_POOL_DATA_PROVIDER = 0x69256C3EB7b657c8aF0d51Cf6e462b09b94C45ec;

  // https://testnet.ftmscan.com/address/0x473b16Fdf6e7017893c4c7AE7843C1F765a6d853
  address internal constant WALLET_BALANCE_PROVIDER = 0x473b16Fdf6e7017893c4c7AE7843C1F765a6d853;

  // https://testnet.ftmscan.com/address/0x37d7ce66F01Bd4B483835cf6982D1988Da5Ed568
  address internal constant WETH_GATEWAY = 0x37d7ce66F01Bd4B483835cf6982D1988Da5Ed568;
}

library AaveV3FantomTestnetAssets {
  // https://testnet.ftmscan.com/address/0xdF0687BCcb6bb7D046d26a5Cf38D81758468ab10
  address internal constant DAI_UNDERLYING = 0xdF0687BCcb6bb7D046d26a5Cf38D81758468ab10;

  uint8 internal constant DAI_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0x2D2771A626DAAd0F1D0b5A1C28db73950d624448
  address internal constant DAI_A_TOKEN = 0x2D2771A626DAAd0F1D0b5A1C28db73950d624448;

  // https://testnet.ftmscan.com/address/0xe22F79d689e5b0e5da6E70B5c1d71e9eC4B8b320
  address internal constant DAI_V_TOKEN = 0xe22F79d689e5b0e5da6E70B5c1d71e9eC4B8b320;

  // https://testnet.ftmscan.com/address/0x29ef8984336D8A2E0A94987E0c14469e1896B479
  address internal constant DAI_S_TOKEN = 0x29ef8984336D8A2E0A94987E0c14469e1896B479;

  // https://testnet.ftmscan.com/address/0xc27c957F734A5E43956d2dd95fe22917c682a85b
  address internal constant DAI_ORACLE = 0xc27c957F734A5E43956d2dd95fe22917c682a85b;

  // https://testnet.ftmscan.com/address/0x26fBAA25ae753F4Ded5BE845E0aD6FCaE773d3e7
  address internal constant DAI_INTEREST_RATE_STRATEGY = 0x26fBAA25ae753F4Ded5BE845E0aD6FCaE773d3e7;

  // https://testnet.ftmscan.com/address/0x7567951F7A80505D0CAa843113834ed4dD0f7Fe5
  address internal constant LINK_UNDERLYING = 0x7567951F7A80505D0CAa843113834ed4dD0f7Fe5;

  uint8 internal constant LINK_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0xc028Ce7431ABa4d621453Fb30b2b2Dd67a79196b
  address internal constant LINK_A_TOKEN = 0xc028Ce7431ABa4d621453Fb30b2b2Dd67a79196b;

  // https://testnet.ftmscan.com/address/0x3CEc44143D90Ac3BE840E5d1f408e832378A628c
  address internal constant LINK_V_TOKEN = 0x3CEc44143D90Ac3BE840E5d1f408e832378A628c;

  // https://testnet.ftmscan.com/address/0xf5649F5Fbc7f2aDca02BEe329176441ee7f0F4Ac
  address internal constant LINK_S_TOKEN = 0xf5649F5Fbc7f2aDca02BEe329176441ee7f0F4Ac;

  // https://testnet.ftmscan.com/address/0x6d5689Ad4C1806D1BA0c70Ab95ebe0Da6B204fC5
  address internal constant LINK_ORACLE = 0x6d5689Ad4C1806D1BA0c70Ab95ebe0Da6B204fC5;

  // https://testnet.ftmscan.com/address/0x1cC884593cf21216cAc9249bE1367df6dAa51513
  address internal constant LINK_INTEREST_RATE_STRATEGY =
    0x1cC884593cf21216cAc9249bE1367df6dAa51513;

  // https://testnet.ftmscan.com/address/0x07BAecfcCd919e54c186554Ab43574519F8d3cfE
  address internal constant USDC_UNDERLYING = 0x07BAecfcCd919e54c186554Ab43574519F8d3cfE;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://testnet.ftmscan.com/address/0xd69EBc885a338CD842eB1B9B3ba9BBf3De609b83
  address internal constant USDC_A_TOKEN = 0xd69EBc885a338CD842eB1B9B3ba9BBf3De609b83;

  // https://testnet.ftmscan.com/address/0xacEF6533C60D5E5f1F168d5B270345b2143C1669
  address internal constant USDC_V_TOKEN = 0xacEF6533C60D5E5f1F168d5B270345b2143C1669;

  // https://testnet.ftmscan.com/address/0xb7c6Ca17D19f107f008f50Cb351b072274ECbDa5
  address internal constant USDC_S_TOKEN = 0xb7c6Ca17D19f107f008f50Cb351b072274ECbDa5;

  // https://testnet.ftmscan.com/address/0x6Ee8DBDF1504225efCB4c79CC681266e147182a2
  address internal constant USDC_ORACLE = 0x6Ee8DBDF1504225efCB4c79CC681266e147182a2;

  // https://testnet.ftmscan.com/address/0x690eC0D0d9C75915E8782C53919dA2E7850C5532
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x690eC0D0d9C75915E8782C53919dA2E7850C5532;

  // https://testnet.ftmscan.com/address/0x8e4Fde5647b31566C1bf8c7AE0f5558aA17b0Cd1
  address internal constant WBTC_UNDERLYING = 0x8e4Fde5647b31566C1bf8c7AE0f5558aA17b0Cd1;

  uint8 internal constant WBTC_DECIMALS = 8;

  // https://testnet.ftmscan.com/address/0xeEe16cE6F70b5f7D6c04bCf6E29FE027611AA745
  address internal constant WBTC_A_TOKEN = 0xeEe16cE6F70b5f7D6c04bCf6E29FE027611AA745;

  // https://testnet.ftmscan.com/address/0xB39ec8c025f8b86682B7d909aE6070B0840FdCc4
  address internal constant WBTC_V_TOKEN = 0xB39ec8c025f8b86682B7d909aE6070B0840FdCc4;

  // https://testnet.ftmscan.com/address/0x2f6B07C57bF2f2AA7fDA7d0Adb5E36A4Ff6565c4
  address internal constant WBTC_S_TOKEN = 0x2f6B07C57bF2f2AA7fDA7d0Adb5E36A4Ff6565c4;

  // https://testnet.ftmscan.com/address/0x65E8d79f3e8e36fE48eC31A2ae935e92F5bBF529
  address internal constant WBTC_ORACLE = 0x65E8d79f3e8e36fE48eC31A2ae935e92F5bBF529;

  // https://testnet.ftmscan.com/address/0x1cC884593cf21216cAc9249bE1367df6dAa51513
  address internal constant WBTC_INTEREST_RATE_STRATEGY =
    0x1cC884593cf21216cAc9249bE1367df6dAa51513;

  // https://testnet.ftmscan.com/address/0x7f0a70f9737EC6B3C3b6Ad93b536f332Eed8a0EF
  address internal constant WETH_UNDERLYING = 0x7f0a70f9737EC6B3C3b6Ad93b536f332Eed8a0EF;

  uint8 internal constant WETH_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0xEF9D79EbC57FE94CEA2157d1789841deD482965c
  address internal constant WETH_A_TOKEN = 0xEF9D79EbC57FE94CEA2157d1789841deD482965c;

  // https://testnet.ftmscan.com/address/0xAcB72f254cA0003E4c0fb5ee9478723D55d7C38A
  address internal constant WETH_V_TOKEN = 0xAcB72f254cA0003E4c0fb5ee9478723D55d7C38A;

  // https://testnet.ftmscan.com/address/0x578a19920eAE5e9e8cFAB1995A982Bf95734360c
  address internal constant WETH_S_TOKEN = 0x578a19920eAE5e9e8cFAB1995A982Bf95734360c;

  // https://testnet.ftmscan.com/address/0xB8C458C957a6e6ca7Cc53eD95bEA548c52AFaA24
  address internal constant WETH_ORACLE = 0xB8C458C957a6e6ca7Cc53eD95bEA548c52AFaA24;

  // https://testnet.ftmscan.com/address/0x1cC884593cf21216cAc9249bE1367df6dAa51513
  address internal constant WETH_INTEREST_RATE_STRATEGY =
    0x1cC884593cf21216cAc9249bE1367df6dAa51513;

  // https://testnet.ftmscan.com/address/0x5904aEF9215D681e2Fcd63040DBb955d24C778EA
  address internal constant USDT_UNDERLYING = 0x5904aEF9215D681e2Fcd63040DBb955d24C778EA;

  uint8 internal constant USDT_DECIMALS = 6;

  // https://testnet.ftmscan.com/address/0x442447221D6cD2E9Ff8e0dB48907a03d1Be2E0B8
  address internal constant USDT_A_TOKEN = 0x442447221D6cD2E9Ff8e0dB48907a03d1Be2E0B8;

  // https://testnet.ftmscan.com/address/0xa734Fb1cA20d4Af01F621cF8196cD38eA6139881
  address internal constant USDT_V_TOKEN = 0xa734Fb1cA20d4Af01F621cF8196cD38eA6139881;

  // https://testnet.ftmscan.com/address/0xC57b3638d50823Fc8D3875E3BC71bA02f6c471D1
  address internal constant USDT_S_TOKEN = 0xC57b3638d50823Fc8D3875E3BC71bA02f6c471D1;

  // https://testnet.ftmscan.com/address/0x9BB8A6dcD83E36726Cc230a97F1AF8a84ae5F128
  address internal constant USDT_ORACLE = 0x9BB8A6dcD83E36726Cc230a97F1AF8a84ae5F128;

  // https://testnet.ftmscan.com/address/0x690eC0D0d9C75915E8782C53919dA2E7850C5532
  address internal constant USDT_INTEREST_RATE_STRATEGY =
    0x690eC0D0d9C75915E8782C53919dA2E7850C5532;

  // https://testnet.ftmscan.com/address/0x8f28c17affc0Fce7C68bfFb130253E93b99Abcba
  address internal constant AAVE_UNDERLYING = 0x8f28c17affc0Fce7C68bfFb130253E93b99Abcba;

  uint8 internal constant AAVE_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0x5fbBdEf9E8139dCdfcd7Cd661dC66245E7c051e1
  address internal constant AAVE_A_TOKEN = 0x5fbBdEf9E8139dCdfcd7Cd661dC66245E7c051e1;

  // https://testnet.ftmscan.com/address/0x9429d2aA9462EF55a7613d93c3923CE121e96f51
  address internal constant AAVE_V_TOKEN = 0x9429d2aA9462EF55a7613d93c3923CE121e96f51;

  // https://testnet.ftmscan.com/address/0xbF3AF4D830050cD9CcFF903b4468719a3fa01A2c
  address internal constant AAVE_S_TOKEN = 0xbF3AF4D830050cD9CcFF903b4468719a3fa01A2c;

  // https://testnet.ftmscan.com/address/0xe41037CA6Dcf2d80a8BB3BccF56B73742d948a26
  address internal constant AAVE_ORACLE = 0xe41037CA6Dcf2d80a8BB3BccF56B73742d948a26;

  // https://testnet.ftmscan.com/address/0x1cC884593cf21216cAc9249bE1367df6dAa51513
  address internal constant AAVE_INTEREST_RATE_STRATEGY =
    0x1cC884593cf21216cAc9249bE1367df6dAa51513;

  // https://testnet.ftmscan.com/address/0x71E10f1BeD205C1212B4d1Ce4a32BdB7295BFbC0
  address internal constant WFTM_UNDERLYING = 0x71E10f1BeD205C1212B4d1Ce4a32BdB7295BFbC0;

  uint8 internal constant WFTM_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0x11f77005Da9a3432c7Fcb6622534Bf4E722f233B
  address internal constant WFTM_A_TOKEN = 0x11f77005Da9a3432c7Fcb6622534Bf4E722f233B;

  // https://testnet.ftmscan.com/address/0x7e85dD96bCc440E6fFeC8E00F7Cd170F12e15cAD
  address internal constant WFTM_V_TOKEN = 0x7e85dD96bCc440E6fFeC8E00F7Cd170F12e15cAD;

  // https://testnet.ftmscan.com/address/0x249261f0746e2D982C07861cF725b0426afA4421
  address internal constant WFTM_S_TOKEN = 0x249261f0746e2D982C07861cF725b0426afA4421;

  // https://testnet.ftmscan.com/address/0xe04676B9A9A2973BCb0D1478b5E1E9098BBB7f3D
  address internal constant WFTM_ORACLE = 0xe04676B9A9A2973BCb0D1478b5E1E9098BBB7f3D;

  // https://testnet.ftmscan.com/address/0x1cC884593cf21216cAc9249bE1367df6dAa51513
  address internal constant WFTM_INTEREST_RATE_STRATEGY =
    0x1cC884593cf21216cAc9249bE1367df6dAa51513;

  // https://testnet.ftmscan.com/address/0x8763ce2AD58Cf589F18d868c43FEfA21BE6310DA
  address internal constant CRV_UNDERLYING = 0x8763ce2AD58Cf589F18d868c43FEfA21BE6310DA;

  uint8 internal constant CRV_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0x45c8618053Bb5399f705Bf14114AfAb676946895
  address internal constant CRV_A_TOKEN = 0x45c8618053Bb5399f705Bf14114AfAb676946895;

  // https://testnet.ftmscan.com/address/0x643cC03Bb528EB59EBEDCC918AF33575655db915
  address internal constant CRV_V_TOKEN = 0x643cC03Bb528EB59EBEDCC918AF33575655db915;

  // https://testnet.ftmscan.com/address/0xfBD4419147f438e893fe992B2491df6DA577e840
  address internal constant CRV_S_TOKEN = 0xfBD4419147f438e893fe992B2491df6DA577e840;

  // https://testnet.ftmscan.com/address/0x3BBCF4313bB1Ac81996094B62Cf2434983191666
  address internal constant CRV_ORACLE = 0x3BBCF4313bB1Ac81996094B62Cf2434983191666;

  // https://testnet.ftmscan.com/address/0x1cC884593cf21216cAc9249bE1367df6dAa51513
  address internal constant CRV_INTEREST_RATE_STRATEGY = 0x1cC884593cf21216cAc9249bE1367df6dAa51513;

  // https://testnet.ftmscan.com/address/0xe733F960BF9Eab5993Dccd61856579939bA2019f
  address internal constant SUSHI_UNDERLYING = 0xe733F960BF9Eab5993Dccd61856579939bA2019f;

  uint8 internal constant SUSHI_DECIMALS = 18;

  // https://testnet.ftmscan.com/address/0x664eD46f40749015279bdcbD7d8773bC7Ae1B866
  address internal constant SUSHI_A_TOKEN = 0x664eD46f40749015279bdcbD7d8773bC7Ae1B866;

  // https://testnet.ftmscan.com/address/0xF57a2892Aa22558F4fAC3d5c52712EC9a7FfEb88
  address internal constant SUSHI_V_TOKEN = 0xF57a2892Aa22558F4fAC3d5c52712EC9a7FfEb88;

  // https://testnet.ftmscan.com/address/0x882e4B066443897EE2BBF7934F3Eac6dE0476120
  address internal constant SUSHI_S_TOKEN = 0x882e4B066443897EE2BBF7934F3Eac6dE0476120;

  // https://testnet.ftmscan.com/address/0xd8c5DaC0A776a1Aa10A3aFb3A0071223ab0ffF53
  address internal constant SUSHI_ORACLE = 0xd8c5DaC0A776a1Aa10A3aFb3A0071223ab0ffF53;

  // https://testnet.ftmscan.com/address/0x1cC884593cf21216cAc9249bE1367df6dAa51513
  address internal constant SUSHI_INTEREST_RATE_STRATEGY =
    0x1cC884593cf21216cAc9249bE1367df6dAa51513;
}

library AaveV3FantomTestnetEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant STABLECOINS = 1;
}
