// AUTOGENERATED - MANUALLY CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {AaveV3FantomTestnet} from './AaveV3FantomTestnet.sol';
import {AaveV3Fantom} from './AaveV3Fantom.sol';
import {MiscFantom} from './MiscFantom.sol';
import {AaveGovernanceV2} from './AaveGovernanceV2.sol';
import {AaveSafetyModule} from './AaveSafetyModule.sol';
